n1 = int(input("Digite um número: "))
n2 = int(input("Digite outro número: "))
s = (n1 + n2)
m = (n1 * n2)
d = (n1/n2)
di = (n1//n2)
e = (n1**n2)
print(f"A soma dos valores é {s} \n a multiplicação é {m} \n e a divisão é {d:.2f} ", end="")
print(f"A divisão inteira é {di} e a potência é {e}")